module.exports = {
  ERR_FETCHING_USER_BY_COGNITO_ID: 'An error occurred while fetching user by ID. Please try again.',
  ERR_FETCHING_USER_BY_PREFERRED: 'An error occurred while fetching user by username. Please try again.',
  ERR_FETCHING_USER_BY_SUB_ID: 'An error occured while fetching your user data.',
  ERR_FETCHING_USER_BY_ID: 'An error occured while fetching your user data.',
  ERR_UPDATING_USER_ATTRIBUTE: 'An error occurred while updating user attributes. Please try again.',
  ERR_UPDATING_PASSWORD: 'An error occurred while updating password. Please try again.',
  USER_DOESNT_EXIST: 'We couldn\'t find this user. Please try again.',
  UPDATE_OUTSIDER_USERNAME: 'Cannot update outsiders data',
  PASSWORD_CHANGED_SUCCESSFULLY: 'Password has been successfully changed',
  ERR_UPDATING_USER_DETAILS: 'Something went wrong while updating user details',
  ERR_FETCHING_ALL_ADMINS: 'Something went wrong while fetching admins',
  ERR_FETCHING_ALL_USERS: 'Something went wrong while fetching user',
  ERR_REWARDABLE_USERS: 'Something went wrong while getting rewardable users',
  ERR_REGISTERING_DEVICE: 'Something went wrong while registering user device',
  ERR_REMOVING_DEVICE: 'Something went wrong while removing user device',
  ERR_UPLOADING_IMAGE: 'Something went wrong while uploading image',
  ERR_GETTING_USER_HISTORY: 'Something went wrong while getting user history',
  ERR_GETTING_ACTIVE_USERS_COUNT: 'Something went wrong while getting active users count'
};
